version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:


services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    depends_on:
      - web
    volumes:
      -  ./nginx/nginx.conf:/etc/nginx/conf.d/default.nginx
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 80:80
    restart: always


