version: "3.8"

volumes:
  postgres_data:
  static_volume:
  media_volume: 


services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./foodgram/.env

  web:
    build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:4000
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - ./foodgram/.env

  nginx:
    build: ./nginx
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
      - "8080:80"
    depends_on:
      - web
    restart: always