# Generated by Django 2.2.6 on 2020-10-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_followrecipe_followuser_shoppinglist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="units",
            new_name="dimension",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="name",
            new_name="title",
        ),
    ]
