# Generated by Django 2.2.6 on 2020-10-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_auto_20201030_2307"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="dimension",
            new_name="units",
        ),
    ]
