# Generated by Django 2.2.6 on 2020-11-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201031_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='text',
            new_name='description',
        ),
    ]
