# Generated by Django 2.2.6 on 2020-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_auto_20201201_1900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.Tag"
            ),
        ),
    ]
