# Generated by Django 2.2.6 on 2020-12-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_auto_20201212_1917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(
                related_name="recipes", to="recipes.Tag"
            ),
        ),
    ]
