name: foodgram_workflow

on:
  push:
     branches:
       - master
 
jobs:  
  build_and_push_to_dockerhub: 
    name: Push docker image to docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sergeidocker/foodgram-project:latest
  deploy:
     runs-on: ubuntu-latest
     needs: build_and_push_to_dockerhub
     steps: 
       - uses: actions/checkout@master
       - name: copy files
         uses: appleboy/scp-action@master
         with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: './.env, ./nginx/nginx.conf, ./nginx/Dockerfile ./Dockerfile, ./docker-compose ./requirements'
          target: "./foodgram-project"

       - name: creating and running container
         uses: appleboy/ssh-action@master
         with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: | 
           sudo cd foodgram-project
           sudo docker-compose stop && sudo docker container prune -f
           sudo docker image rm sergeidocker/foodgram-project:latest
           sudo docker-compose up -d --build
           
  send_message:
     runs-on: ubuntu-latest
     needs: deploy
     steps:
     - name: send message
       uses: appleboy/telegram-action@master
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: $ Foodgram workflow успешно выполнен!
